# Generated by Django 5.0.1 on 2024-01-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(blank=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("pool_report", models.BooleanField()),
                ("publish", models.BooleanField()),
                ("off_the_record", models.BooleanField()),
                (
                    "review_status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Complete"),
                        ],
                        default="Unspecified",
                        verbose_name="Editorial Review",
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=1000, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
